### ISSUE TITLE
Please, add babel/runtime to external

### ISSUE THREAD

**Issue by ludmiloff** [jaebradley/example-rollup-react-component-npm-package#102]
Thank you for your effort.
Please, make sure babel/runtime is externalised as stated in [@rollup/plugin-babel](https://github.com/rollup/plugins/tree/master/packages/babel) docs when using 

`babelHelpers: 'runtime'`

> ... you should use this especially when building libraries with Rollup. It has to be used in combination with @babel/plugin-transform-runtime and you should also specify @babel/runtime as dependency of your package. Don't forget to tell Rollup to treat the helpers imported from within the @babel/runtime module as external dependencies when bundling for cjs & es formats. This can be accomplished via regex (external: [/@babel\/runtime/])

**Comment by jaebradley** [comment]
@ludmiloff thanks for reporting this issue and sorry for the delay in resolving this issue - I hope that #104 resolves this sufficiently.

If not, please let me know and I'll be happy to continue working on this issue.
