### ISSUE TITLE
css not being loaded

### ISSUE THREAD

**Issue by uriklar** [jaebradley/example-rollup-react-component-npm-package#52]
Hi @jaebradley ,
Thanks for the example! I'm trying to get my component lib to work with rollup and sass without success. 
I cloned your repo, ran the build, and imported <AnExample /> in a CRA I created and you css for the `an-example` class isn't being loaded in my app. Which is the exact same issue I'm having with my lib...

Do you know what i'm doing wrong? Have you tried actually consuming these example components in an app and can verify the css get's injected?

Many thanks!
Uri

**Comment by jaebradley** [comment]
Hey @uriklar, thanks for reaching out!

You can see the example components and CSS being utilized here: https://stackblitz.com/edit/example-rollup-react-component-npm-package?file=package.json

![image](https://user-images.githubusercontent.com/8136030/62062421-d7ec7f00-b1dd-11e9-8032-76167136af1b.png)

**Comment by uriklar** [comment]
Hi @jaebradley. Thanks for the ultra quick response :-)
It was my mistake. I wasn't aware I need to import the css separately.

**Comment by jaebradley** [comment]
@uriklar no worries - it's not particular clear from the `README` that the CSS is built / imported separately. I'm hoping to add some more documentation in the future.

Cheers!

**Comment by uriklar** [comment]
While we're here.. I was wondering if during your research you've found a good resource on building a tree shakable component library with Rollup (or even Webpack)?
I'm trying to achieve that and though i've marked "sideEffects": false it seams like my consumer app is getting the whole bundle regardless of what i'm importing. 
Thanks again for the response and for the great example!

**Comment by jaebradley** [comment]
@uriklar are you tree-shaking ES6 modules only? Or are you transpiling ES6 modules into CommonJS?

**Comment by uriklar** [comment]
The latter, transpiling to common js too

**Comment by jaebradley** [comment]
I think you need to tell Babel _not_ to transpile ES6 modules so you can take advantage of static analysis.

![image](https://user-images.githubusercontent.com/8136030/62104727-31dc5b80-b255-11e9-87bd-9018618a054e.png)

https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking/

I could definitely be missing the ball on something as I don't know exactly what your setup is.

**Comment by uriklar** [comment]
Thanks a lot! I'll try it out
